### ISSUE TITLE
能否支持获取js执行之后的网页

### ISSUE THREAD

**Issue by Gethin-H** [xuxueli/xxl-crawler#9]
类似下面那样，或者是js生成的节点。
`
<script type="text/javascript">
    document.getElementById("abc").src = "xxx";
</script>
`

**Comment by wysnxzm** [comment]
已提供基于htmlUtil下载器

**Comment by xuxueli** [comment]
你好，感谢关注哈！
已支持JS渲染方式采集数据。得益于模块化结构设计，可自由扩展其他 "PageLoader" 实现，如 "Selenium" 方式等；
